pipeline {
    agent any
    stages {
        stage('Install python3') {
            steps {
                sh 'sudo apt-get update'
            }
        }
        stage('Install pyats') {
            steps {
                sh 'sudo apt-get install python3.6'
            }        
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
